schools_dict = {
    "big_ten" : ['Illinois', 'Indiana', 'Iowa', 'Maryland', 'Michigan', 'Michigan State', 'Minnesota', 'Nebraska', 'Northwestern', 'Ohio State', 'Penn State', 'Purdue', 'Rutgers', 'Wisconsin'],
    "big_twelve" : ['Baylor', 'Iowa State', 'Kansas', 'Kansas State', 'Oklahoma', 'Oklahoma State', 'TCU', 'Texas', 'Texas Tech', 'West Virginia'],
    "acc" : ['Boston College', 'Clemson', 'Duke', 'Florida State', 'Georgia Tech', 'Louisville', 'Miami Florida', 'North Carolina', 'North Carolina State', 'Notre Dame', 'Pittsburgh', 'Syracuse', 'Virginia', 'Virginia Tech', 'Wake Forest'],
    "sec" : ['Alabama', 'Arkansas', 'Auburn', 'Florida', 'Georgia', 'Kentucky', 'LSU', 'Mississippi', 'Mississippi State', 'Missouri', 'South Carolina', 'Tennessee', 'Texas A&M', 'Vanderbilt'],
    "pac_twelve" : ['Arizona', 'Arizona State', 'California', 'Colorado', 'Oregon', 'Oregon State', 'Stanford', 'UCLA', 'USC', 'Utah', 'Washington', 'Washington State'],
    "hbcu" : ['Alabama A&M', 'Alabama State', 'Alcorn State', 'Arkansas-Pine Bluff', 'Bethune-Cookman', 'Coppin State', 'Delaware State', 'Florida A&M', 'Grambling State', 'Howard', 'Jackson State', 'Maryland-Eastern Shore', 'Mississippi Valley State', 'Morgan State', 'Norfolk State', 'North Carolina A&T', 'North Carolina Central', 'Prairie View A&M', 'South Carolina State', 'Southern', 'Texas Southern'],
    "big_west" : ['Cal Poly', 'Cal State Fullerton', 'Cal State Northridge', 'Hawaii', 'Long Beach State', 'UC Davis', 'UC Irvine', 'UC Riverside', 'UC Santa Barbara'],
    "big_sky" : ['Eastern Washington', 'Idaho', 'Idaho State', 'Montana', 'Montana State', 'North Dakota', 'Northern Arizona', 'Northern Colorado', 'Portland State', 'Sacramento State', 'Southern Utah', 'Weber State'],
    "big_south" : ['Campbell', 'Charleston Southern', 'Gardner-Webb', 'High Point', 'Liberty', 'Longwood', 'Presbyterian', 'Radford', 'UNC Asheville', 'UNC Greensboro', 'VMI', 'Winthrop'],
    "big_east" : ['Butler', 'Creighton', 'DePaul', 'Georgetown', 'Marquette', 'Providence', 'Seton Hall', 'St. John\'s (NY)', 'Villanova', 'Xavier'],
    "ivy" : ['Brown', 'Columbia', 'Cornell', 'Dartmouth', 'Harvard', 'Pennsylvania', 'Princeton', 'Yale'],
    "maac" : ['Canisius', 'Fairfield', 'Iona', 'Manhattan', 'Marist', 'Monmouth', 'Niagara', 'Quinnipiac', 'Rider', 'Saint Peter\'s', 'Siena'],
    "ohio_valley" : ['Austin Peay', 'Belmont', 'Eastern Illinois', 'Eastern Kentucky', 'Jacksonville State', 'Morehead State', 'Murray State', 'Southeast Missouri State', 'Southern Illinois-Edwardsville', 'Tennessee State', 'Tennessee Tech', 'UT Martin'],
    "patriot" : ['American', 'Army', 'Boston University', 'Bucknell', 'Colgate', 'Holy Cross', 'Lafayette', 'Lehigh', 'Loyola (MD)', 'Navy'],
    "sun_belt" : ['Appalachian State', 'Arkansas-Little Rock', 'Arkansas State', 'Coastal Carolina', 'Georgia Southern', 'Georgia State', 'Louisiana-Lafayette', 'Louisiana-Monroe', 'South Alabama', 'Texas-Arlington', 'Texas State', 'Troy'],
    "west_coast_conf" : ['Brigham Young', 'Gonzaga', 'Loyola Marymount', 'Pacific', 'Pepperdine', 'Portland', 'Saint Mary\'s (CA)', 'San Diego', 'San Francisco', 'Santa Clara'],
    "western_athletic" : ['Cal State Bakersfield', 'Chicago State', 'Grand Canyon', 'Missouri-Kansas City', 'New Mexico State', 'Seattle', 'Texas-Rio Grande Valley', 'Utah Valley'],
    "southland" : ['Abilene Christian', 'Central Arkansas', 'Houston Baptist', 'Incarnate Word', 'Lamar', 'McNeese State', 'New Orleans', 'Nicholls State', 'Northwestern State', 'Sam Houston State', 'Southeastern Louisiana', 'Stephen F. Austin', 'Texas A&M-Corpus Christi'],
    "northeast_conf" : ['Bryant', 'Central Connecticut State', 'Fairleigh Dickinson', 'LIU-Brooklyn', 'Mount St. Mary\'s', 'Robert Morris', 'Sacred Heart', 'St. Francis (NY)', 'St. Francis (PA)', 'Wagner'],
    "missouri_valley" : ['Bradley', 'Drake', 'Evansville', 'Illinois State', 'Indiana State', 'Loyola (IL)', 'Missouri State', 'Northern Iowa', 'Southern Illinois', 'Valparaiso'],
    "northeast_conf" : ['Bryant', 'Central Connecticut State', 'Fairleigh Dickinson', 'LIU-Brooklyn', 'Mount St. Mary\'s', 'Robert Morris', 'Sacred Heart', 'St. Francis (NY)', 'St. Francis (PA)', 'Wagner'],
    "conference_usa" : ['Charlotte', 'Florida Atlantic', 'Florida International', 'Louisiana Tech', 'Marshall', 'Middle Tennessee', 'North Texas', 'Old Dominion', 'Rice', 'Southern Mississippi', 'Texas-El Paso', 'Texas-San Antonio', 'Western Kentucky'],
    "horizon_league" : ['Cleveland State', 'Detroit Mercy', 'Green Bay', 'Illinois-Chicago', 'IUPUI', 'Milwaukee', 'Northern Kentucky', 'Oakland', 'Wright State', 'Youngstown State'],
    "mid_american" : ['Akron', 'Ball State', 'Bowling Green State', 'Buffalo', 'Central Michigan', 'Eastern Michigan', 'Kent State', 'Miami Ohio', 'Northern Illinois', 'Ohio', 'Toledo', 'Western Michigan'],
    "asun" : ['Florida Gulf Coast', 'Jacksonville', 'Kennesaw State', 'Lipscomb', 'New Jersey Tech', 'North Florida', 'South Carolina Upstate', 'Stetson'],
    "america_east" : ['Albany (NY)', 'Binghamton', 'Hartford', 'Maine', 'Massachusetts-Lowell', 'New Hampshire', 'Stony Brook', 'UMBC', 'Vermont'],
    "american_athletic" : ['Central Florida', 'Cincinnati', 'Connecticut', 'East Carolina', 'Houston', 'Memphis', 'South Florida', 'Southern Methodist', 'Temple', 'Tulane', 'Tulsa'],
    }